### ISSUE TITLE
Missing tokens from Metamask Balance

### ISSUE THREAD

**Issue by bazzar54** [PonzioTheCat/contracts#1]
Hi I bought 356 Ponzio tokens via uniswap and the TX hash confirms purchase.  However the balance is only showing 110 tokens so where has the 246 tokens dissapeared to?  Ive spoken with Metamask who confirms the balance should and still show the correct amount but its definatley not there.  Can you help?

TX 0xe21be816dfd3691de397e7ae42628d5c43fbd730b816003e4b5408b04905c569

Screenshot of Etherscan:
<img width="1440" alt="Screenshot 2024-07-07 at 12 57 49" src="https://github.com/PonzioTheCat/contracts/assets/76653882/041e4fb0-814c-48e3-bae3-45fc9426d44f">

**Comment by bazzar54** [comment]
I also dont understand this transaction?  See TX and screen shot for details below:
0x2905f9628fa91b649acce4ab1973b8404e6d4654
<img width="1440" alt="Screenshot 2024-07-07 at 13 03 27" src="https://github.com/PonzioTheCat/contracts/assets/76653882/799d4b61-9ad0-4ec9-80e9-69b88c912d5e">
cd511a72c96b62ad31d4f1c7

**Comment by OnlyWhys** [comment]
Correct me if I'm wrong. Have a great day

**Comment by DApps-Representative** [comment]
> Hi I bought 356 Ponzio tokens via uniswap and the TX hash confirms purchase. However the balance is only showing 110 tokens so where has the 246 tokens dissapeared to? Ive spoken with Metamask who confirms the balance should and still show the correct amount but its definatley not there. Can you help?
> 
> TX 0xe21be816dfd3691de397e7ae42628d5c43fbd730b816003e4b5408b04905c569
> 
> Screenshot of Etherscan: <img alt="Screenshot 2024-07-07 at 12 57 49" width="1440" src="https://private-user-images.githubusercontent.com/76653882/346332652-041e4fb0-814c-48e3-bae3-45fc9426d44f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5ODA5MjAsIm5iZiI6MTcyMDk4MDYyMCwicGF0aCI6Ii83NjY1Mzg4Mi8zNDYzMzI2NTItMDQxZTRmYjAtODE0Yy00OGUzLWJhZTMtNDVmYzk0MjZkNDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDE4MTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNWU0OWM5YTgzYWU5YTk1Yjc1ZjY4MTRiN2VlODQxYTY4NDY4MjRlZDlhNzMzMzA3Nzk2Yjc3MzZiNzhiNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pG0u4CwQwFOMK7eEpCQCNQ9XYa3dtS_EOUZFb1lpu-o">

Hey there @bazzar54   ,

Thank you for reaching out! hi, it seems your address was blacklisted: kindly refresh your wallet, if the issue persists,then your query would be best dealt with by the support team.
 I’ll have to refer you to Ponzio official support Team with the ticket ID PNZ7463
 
Please see the link below to our dedicated support line: 
 [Ponzio Network Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.

**Comment by nskk-oo** [comment]
我的代币突然减少了 是怎么回事

**Comment by Tunki1201** [comment]
Dear Ponzio team

I want to join the revolution of NGD (Never Going Down) technology and embrace the absurdity of the Ponzio token. As someone who enjoys a good laugh and isn't afraid to dive into high-risk investments, I believe the Ponzio token is the perfect fit for me.

With my (possibly fictitious) IQ of 300, I'm ready to engage with like-minded individuals who appreciate both genius and madness in the world of meme coins. I'm ready to be part of this unique project and contribute to its success.

Disclaimer acknowledged—I'll be sure to do my own research and tread carefully in this wild ride.

Looking forward to the journey ahead!

https://pepe-demo.vercel.app/

**Comment by bazzar54** [comment]
Is anyone here from the support team at Ponzio??

**Comment by PonzioTheCat** [comment]
The PONZIO token is a debase token, every 4 days the supply is divided by two. Which means all wallets balance is divided 2 and the price is multiplied by 2 (so users don't loose any value due to the debase mechanism). This mechanism is linearised to be executed 168 times during the 4 days, so a small debase occurs approximately every 34minutes. 
Also, 13.37% more of the debased amount is sent to the staking. Which means that if you add liquidity and stake your UNIV2-LP token you get back your 13.37% lost at each debase.

Due to the debase mechanism, your balance will decrease over the time, again, it doesn't mean you have loose values because the price goes always up. Your actual balance on etherscan might be wrong, etherscan don't compute correctly the balance due to the debase. Metamask should update it correctly but if you want to see your real balance, go to [ponzio.io](https://ponzio.io). The website is optimised to correctly compute the user balance and correctly compute the swap / liquidity add or remove / staking.

**Comment by Tunki1201** [comment]
Hey, What I want to say is that I want to work with your community.
